spring.application.name=inbox-pilot
spring.main.banner-mode=off
spring.profiles.active=secret

ai.base-url=https://api.aicredits.in/v1
#ai.model=meta-llama/llama-3.1-8b-instruct
#ai.model=mistralai/ministral-8b-2512
ai.model=openai/gpt-oss-20b
spring.config.import=optional:classpath:application-secret.properties
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

ai.vision-model=google/gemma-3-4b-it